/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_mephi_dozen_rshamyan_adaliquid_gpgpu_JCulzss */

#ifndef _Included_ru_mephi_dozen_rshamyan_adaliquid_gpgpu_JCulzss
#define _Included_ru_mephi_dozen_rshamyan_adaliquid_gpgpu_JCulzss
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_mephi_dozen_rshamyan_adaliquid_gpgpu_JCulzss
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_mephi_dozen_rshamyan_adaliquid_gpgpu_JCulzss_encode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ru_mephi_dozen_rshamyan_adaliquid_gpgpu_JCulzss
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_mephi_dozen_rshamyan_adaliquid_gpgpu_JCulzss_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
